### ISSUE TITLE
Text Normalization for Turkish Language using the Normalizer Class

### ISSUE THREAD

**Issue by TarikKaanKoc** [tnltk/tnltk#1]
### Tasks
Create a Normalizer class, he script should contain the following steps:

1. Convert the input text to lowercase using the lower_case() function, making sure to properly handle Turkish characters such as "İ", "I", "Ğ", "Ü", "Ö", "Ş", and "Ç".
2. Remove punctuation marks from the text using the remove_punctuations() function.
3. Remove accent marks from the text using the remove_accent_marks() function.
4. Deasciify the text using the deasciify() function, which uses Emre Sevinç's implementation.
5. Correct any typographical errors in the text using the correct_typos() function.
6. Convert numbers in the text to word form using the convert_numbers_to_words() function.
7. Save the normalized text to a file or print the result to the console.

<div class="min-h-[20px] flex flex-col items-start gap-4 whitespace-pre-wrap"><div class="markdown prose w-full break-words dark:prose-invert dark"><table><thead><tr><th>Step</th><th>Function</th></tr></thead><tbody><tr><td>1</td><td>lower_case()</td></tr><tr><td>2</td><td>remove_punctuations()</td></tr><tr><td>3</td><td>remove_accent_marks()</td></tr><tr><td>4</td><td>deasciify()</td></tr><tr><td>5</td><td>correct_typos()</td></tr><tr><td>6</td><td>convert_numbers_to_words()</td></tr><tr><td>7</td><td>save the normalized text to a file or print the result to the console</td></tr></tbody></table></div></div>

**Note:** The task is based on the assumption that the class and all the functions are implemented and functional. (You do not have to be bound to this task. You can add and expand on it.)

**Comment by TarikKaanKoc** [comment]
###  Normalizing Turkish Text: A Checklist of Tasks
-----

- [x] Convert the input text to lowercase using the lower_case() function, making sure to properly handle Turkish characters such as "İ", "I", "Ğ", "Ü", "Ö", "Ş", and "Ç".
- [x] Remove punctuations from the given text using the remove_punctuations() function.
- [x] Remove accent marks from the given text using the remove_accent_marks() function.
- [ ] Perform spelling/typo correction on the input text using the correct_typos() function.
- [ ] Convert numbers in the input text to their word form using the number_to_word() function.
- [ ] Deasciify the input text for Turkish using the deasciify() function.

**Comment by TarikKaanKoc** [comment]
updated docs: https://github.com/tnltk/tnltk/commit/1b73e5eec3dc01b878a0f3678b7c663f65723a70

**Comment by sfurkan20** [comment]
> ### Normalizing Turkish Text: A Checklist of Tasks
> * [x]  Convert the input text to lowercase using the lower_case() function, making sure to properly handle Turkish characters such as "İ", "I", "Ğ", "Ü", "Ö", "Ş", and "Ç".
> * [x]  Remove punctuations from the given text using the remove_punctuations() function.
> * [x]  Remove accent marks from the given text using the remove_accent_marks() function.
> * [ ]  Perform spelling/typo correction on the input text using the correct_typos() function.
> * [ ]  Convert numbers in the input text to their word form using the number_to_word() function.
> * [ ]  Deasciify the input text for Turkish using the deasciify() function.
> 
> commit: [efb4963](https://github.com/tnltk/tnltk/commit/efb4963140896dbdff4e1e9f1e56d86bbbc833a4)

I did not quite understand whether the desired methods are currently implemented, for instance, isn't `convert_to_turkish()` presently doing the expected thing from `deasciify()`, or has there been a renaming?

BTW, thanks a lot for taking the initiative for such a project!

**Comment by TarikKaanKoc** [comment]
You got it right @sfurkan20 ! Thank you for your support in this project. After reviewing the available functions, I decided that the  ``'deasciify.py'`` script should be marked as internal use only and renamed to  ``'_deasciify.py'`` to indicate that it should not be used directly.

**That's why I added the deasciify function to the task.**

**Comment by TarikKaanKoc** [comment]
### Update on the 'normalizer' & 'deasciify' script 
----
https://github.com/tnltk/tnltk/commit/8368340a0ee15369f9e081c0f3b79044df1b5e2c
